# To execute this docker-compose yml file use `docker-compose.yml -f docker-compose.up`
version: "3"
services:
  yandexsearch-tests:
    image: yandexsearch-tests
    environment:
      - SELENIDE_REMOTE=http://chrome:4444/wd/hub
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"