# To execute this docker-compose yml file use `docker-compose.yml -f docker-compose.yml-v3-dev.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose.yml -f docker-compose.yml-v3-dev.yml down`
version: "3"
services:
  yandexsearch-tests:
    image: yandexsearch-tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SELENIDE_REMOTE=http://chrome:4444/wd/hub
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"